import { WORKER_POOL } from "../constants.js";

// Downloads the full report as a styled HTML file that opens print dialog
// Uses Blob URL — works in all browsers including sandboxed environments
export function downloadReport(goal, synthOutput, workerOutputs, tasks) {
  const timestamp = new Date().toLocaleString();

  const agentSections = tasks
    .map(task => {
      const agent  = WORKER_POOL[task.id];
      const output = workerOutputs[task.id];
      if (!agent || !output) return "";
      return `
        <div class="agent-section">
          <h3>${agent.icon} ${agent.name} <span class="role">${agent.role}</span></h3>
          <pre>${escapeHtml(output)}</pre>
        </div>`;
    })
    .join("");

  // Parse sections from synth output for nice formatting
  const reportSections = parseSections(synthOutput);
  const reportHtml = reportSections.length > 0
    ? reportSections.map(sec => `
        <div class="report-section">
          <h3>${sec.title}</h3>
          ${sec.lines.map(l => `<p class="bullet">• ${escapeHtml(l.replace(/^[•\-]\s*/,""))}</p>`).join("")}
        </div>`).join("")
    : `<pre>${escapeHtml(synthOutput)}</pre>`;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>AgentFlow Report — ${escapeHtml(goal)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Georgia, 'Times New Roman', serif; max-width: 860px; margin: 40px auto; color: #1a1a2e; line-height: 1.7; padding: 0 24px; }
    .header { border-bottom: 3px solid #6366F1; padding-bottom: 20px; margin-bottom: 32px; }
    .logo { display: flex; align-items: center; gap: 10px; margin-bottom: 12px; }
    .logo-icon { width: 40px; height: 40px; background: #6366F1; border-radius: 8px; display: flex; align-items: center; justify-content: center; color: white; font-size: 20px; }
    .logo-text { font-size: 24px; font-weight: 800; color: #6366F1; font-family: Arial, sans-serif; }
    .meta { color: #64748B; font-size: 14px; font-family: Arial, sans-serif; }
    .meta strong { color: #1a1a2e; }
    h2 { font-size: 18px; font-family: Arial, sans-serif; color: #374151; margin: 40px 0 16px; padding-bottom: 8px; border-bottom: 1px solid #E5E7EB; text-transform: uppercase; letter-spacing: 0.5px; }
    .agent-section { margin: 20px 0; padding: 16px 20px; background: #F8FAFC; border-radius: 8px; border-left: 3px solid #6366F1; }
    .agent-section h3 { font-size: 15px; font-family: Arial, sans-serif; color: #6366F1; margin-bottom: 8px; }
    .agent-section .role { color: #64748B; font-weight: 400; font-size: 13px; }
    .agent-section pre { white-space: pre-wrap; font-family: Georgia, serif; font-size: 14px; color: #374151; line-height: 1.75; }
    .report-section { margin: 20px 0; padding: 20px 24px; background: #F1F5F9; border-radius: 10px; }
    .report-section h3 { font-size: 14px; font-family: Arial, sans-serif; font-weight: 700; color: #0F172A; margin-bottom: 12px; text-transform: uppercase; letter-spacing: 1px; }
    .bullet { font-size: 14px; color: #374151; margin: 8px 0; padding-left: 12px; line-height: 1.65; }
    .footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #E5E7EB; color: #94A3B8; font-size: 12px; text-align: center; font-family: Arial, sans-serif; }
    @media print {
      body { margin: 0; padding: 20px; }
      .agent-section, .report-section { break-inside: avoid; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">
      <div class="logo-icon">⚡</div>
      <div class="logo-text">AgentFlow</div>
    </div>
    <div class="meta">
      <strong>Mission:</strong> ${escapeHtml(goal)}<br/>
      <strong>Generated:</strong> ${timestamp}<br/>
      <strong>Platform:</strong> AgentFlow Multi-Agent AI · Powered by LLaMA 3.3 70B
    </div>
  </div>

  <h2>Agent Analyses</h2>
  ${agentSections || "<p style='color:#94A3B8'>No agent data available.</p>"}

  <h2>Executive Report</h2>
  ${reportHtml}

  <div class="footer">
    Generated by AgentFlow · Multi-Agent AI Platform · ${timestamp}
  </div>

  <script>window.onload = () => window.print();</script>
</body>
</html>`;

  // Use Blob URL — works everywhere, no popup blocker issues
  const blob = new Blob([html], { type: "text/html" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = `agentflow-report-${Date.now()}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function escapeHtml(str = "") {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function parseSections(output) {
  const HEADERS = ["EXECUTIVE SUMMARY","KEY INSIGHTS","ACTION PLAN","SUCCESS KPIS","RISK MATRIX"];
  const sections = [];
  let current = null;
  output.split("\n").forEach(line => {
    const t = line.trim();
    if (HEADERS.includes(t)) {
      if (current) sections.push(current);
      current = { title: t, lines: [] };
    } else if (current && t) {
      current.lines.push(t);
    }
  });
  if (current) sections.push(current);
  return sections;
}
